//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumLanguage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EnumLanguage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng đã kích hoạt.
        /// </summary>
        internal static string ActiveUser {
            get {
                return ResourceManager.GetString("ActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người quản lý.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Tuổi từ&quot; không được lớn hơn &quot;Tuổi đến&quot;.
        /// </summary>
        internal static string AgeFromIsNotLargerThanAgeTo {
            get {
                return ResourceManager.GetString("AgeFromIsNotLargerThanAgeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng trong năm phải nằm trong khoảng 1 - 12.
        /// </summary>
        internal static string BirthDayMonthIsOutOfRange {
            get {
                return ResourceManager.GetString("BirthDayMonthIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người nhận đặt hàng.
        /// </summary>
        internal static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thương hiệu.
        /// </summary>
        internal static string BrandManager {
            get {
                return ResourceManager.GetString("BrandManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi thêm.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_Add {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền chi.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_Amount {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đồng ý.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_ApprovedPerson {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_ApprovedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_Category {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_Date {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung thu/chi.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_Description {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người đăng nhập.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_LoggedPerson {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_LoggedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_Order {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người thu/chi.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_PaidPerson {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_PaidPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_Type {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang chờ duyệt.
        /// </summary>
        internal static string CostManagement_IncomeExpenditure_Waitting {
            get {
                return ResourceManager.GetString("CostManagement_IncomeExpenditure_Waitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản thất bại! Xin vui lòng thử lại.
        /// </summary>
        internal static string CreateAccountFailed {
            get {
                return ResourceManager.GetString("CreateAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản thành công!.
        /// </summary>
        internal static string CreateAccountSuccessfully {
            get {
                return ResourceManager.GetString("CreateAccountSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm khách hàng thất bại! Xin thử lại!.
        /// </summary>
        internal static string CreateCustomerFailed {
            get {
                return ResourceManager.GetString("CreateCustomerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm khách hàng thành công!.
        /// </summary>
        internal static string CreateCustomerSuccessfully {
            get {
                return ResourceManager.GetString("CreateCustomerSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại khách hàng thất bại! Vui lòng thử lại.
        /// </summary>
        internal static string CreateCustomerTypeFailed {
            get {
                return ResourceManager.GetString("CreateCustomerTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại khách hàng thành công!.
        /// </summary>
        internal static string CreateCustomerTypeSuccessfully {
            get {
                return ResourceManager.GetString("CreateCustomerTypeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bộ lọc thất bại! Xin thử lại!.
        /// </summary>
        internal static string CreateFilterFailed {
            get {
                return ResourceManager.GetString("CreateFilterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bộ lọc thành công!.
        /// </summary>
        internal static string CreateFilterSuccessfully {
            get {
                return ResourceManager.GetString("CreateFilterSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhà cung cấp thất bại! Vui lòng thử lại.
        /// </summary>
        internal static string CreateVoucherProviderFailed {
            get {
                return ResourceManager.GetString("CreateVoucherProviderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhà cung cấp thành công!.
        /// </summary>
        internal static string CreateVoucherProviderSuccessfully {
            get {
                return ResourceManager.GetString("CreateVoucherProviderSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý khách hàng.
        /// </summary>
        internal static string CRM {
            get {
                return ResourceManager.GetString("CRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá tài khoản thất bại! Xin vui lòng thử lại.
        /// </summary>
        internal static string DeleteAccountFailed {
            get {
                return ResourceManager.GetString("DeleteAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá tài khoản thành công!.
        /// </summary>
        internal static string DeleteAccountSuccessfully {
            get {
                return ResourceManager.GetString("DeleteAccountSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá khách hàng thất bại! Xin thử lại!.
        /// </summary>
        internal static string DeleteCustomerFailed {
            get {
                return ResourceManager.GetString("DeleteCustomerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá khách hàng thành công!.
        /// </summary>
        internal static string DeleteCustomerSuccessfully {
            get {
                return ResourceManager.GetString("DeleteCustomerSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá loại khách hàng thất bại! Vui lòng thử lại.
        /// </summary>
        internal static string DeleteCustomerTypeFailed {
            get {
                return ResourceManager.GetString("DeleteCustomerTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa loại khách hàng thành công!.
        /// </summary>
        internal static string DeleteCustomerTypeSuccessfully {
            get {
                return ResourceManager.GetString("DeleteCustomerTypeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá bộ lọc thất bại! Xin thử lại!.
        /// </summary>
        internal static string DeleteFilterFailed {
            get {
                return ResourceManager.GetString("DeleteFilterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá bộ lọc thành công!.
        /// </summary>
        internal static string DeleteFilterSuccessfully {
            get {
                return ResourceManager.GetString("DeleteFilterSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá nhà cung cấp thất bại! Vui lòng thử lại.
        /// </summary>
        internal static string DeleteVoucherProviderFailed {
            get {
                return ResourceManager.GetString("DeleteVoucherProviderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá nhà cung cấp thành công!.
        /// </summary>
        internal static string DeleteVoucherProviderSuccessfully {
            get {
                return ResourceManager.GetString("DeleteVoucherProviderSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin tài khoản thất bại! Xin vui lòng thử lại.
        /// </summary>
        internal static string EditAccountFailed {
            get {
                return ResourceManager.GetString("EditAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin tài khoản thành công!.
        /// </summary>
        internal static string EditAccountSuccessfully {
            get {
                return ResourceManager.GetString("EditAccountSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin khách hàng thất bại! Vui lòng thử lại!.
        /// </summary>
        internal static string EditCustomerFailed {
            get {
                return ResourceManager.GetString("EditCustomerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin khách hàng thành công!.
        /// </summary>
        internal static string EditCustomerSuccessfully {
            get {
                return ResourceManager.GetString("EditCustomerSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa loại khách hàng thất bại! Vui lòng thử lại.
        /// </summary>
        internal static string EditCustomerTypeFailed {
            get {
                return ResourceManager.GetString("EditCustomerTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa loại khách hàng thành công!.
        /// </summary>
        internal static string EditCustomerTypeSuccessfully {
            get {
                return ResourceManager.GetString("EditCustomerTypeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bộ lọc thất bại! Xin thử lại!.
        /// </summary>
        internal static string EditFilterFailed {
            get {
                return ResourceManager.GetString("EditFilterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa bộ lọc thành công!.
        /// </summary>
        internal static string EditFilterSuccessfully {
            get {
                return ResourceManager.GetString("EditFilterSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nhà cung cấp thất bại! Vui lòng thử lại.
        /// </summary>
        internal static string EditVoucherProviderFailed {
            get {
                return ResourceManager.GetString("EditVoucherProviderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nhà cung cấp thành công!.
        /// </summary>
        internal static string EditVoucherProviderSuccessfully {
            get {
                return ResourceManager.GetString("EditVoucherProviderSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, xin vui lòng liên hệ admin!.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thu chi.
        /// </summary>
        internal static string HouseKeeping {
            get {
                return ResourceManager.GetString("HouseKeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản kho.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý thu chi.
        /// </summary>
        internal static string Menu_HouseKeeping_IncomeExpenditure {
            get {
                return ResourceManager.GetString("Menu_HouseKeeping_IncomeExpenditure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý sản phẩm.
        /// </summary>
        internal static string ProductManager {
            get {
                return ResourceManager.GetString("ProductManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu ngân.
        /// </summary>
        internal static string Reception {
            get {
                return ResourceManager.GetString("Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý cửa hàng.
        /// </summary>
        internal static string StoreManager {
            get {
                return ResourceManager.GetString("StoreManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem báo cáo cửa hàng.
        /// </summary>
        internal static string StoreReportViewer {
            get {
                return ResourceManager.GetString("StoreReportViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý hệ thống.
        /// </summary>
        internal static string SysAdmin {
            get {
                return ResourceManager.GetString("SysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tại quán.
        /// </summary>
        internal static string View_AtStore {
            get {
                return ResourceManager.GetString("View_AtStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy sau chế biến.
        /// </summary>
        internal static string View_Cancel {
            get {
                return ResourceManager.GetString("View_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao hàng.
        /// </summary>
        internal static string View_Delivery {
            get {
                return ResourceManager.GetString("View_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        internal static string View_Finish {
            get {
                return ResourceManager.GetString("View_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới.
        /// </summary>
        internal static string View_New {
            get {
                return ResourceManager.GetString("View_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng Online.
        /// </summary>
        internal static string View_OnlineProduct {
            get {
                return ResourceManager.GetString("View_OnlineProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nạp thẻ.
        /// </summary>
        internal static string View_OrderCard {
            get {
                return ResourceManager.GetString("View_OrderCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy sau chế biến.
        /// </summary>
        internal static string View_PosCancel {
            get {
                return ResourceManager.GetString("View_PosCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        internal static string View_PosFinished {
            get {
                return ResourceManager.GetString("View_PosFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy trước chế biến.
        /// </summary>
        internal static string View_PosPreCancel {
            get {
                return ResourceManager.GetString("View_PosPreCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy trước chế biến.
        /// </summary>
        internal static string View_PreCancel {
            get {
                return ResourceManager.GetString("View_PreCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        internal static string View_Processing {
            get {
                return ResourceManager.GetString("View_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mang đi.
        /// </summary>
        internal static string View_TakeAway {
            get {
                return ResourceManager.GetString("View_TakeAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Số lần đến cửa hàng từ&quot; phải nhỏ hơn &quot;Số lần đến cửa hàng đến&quot;!.
        /// </summary>
        internal static string VisitTimesFromMustNotLargerThanVisitTimesTo {
            get {
                return ResourceManager.GetString("VisitTimesFromMustNotLargerThanVisitTimesTo", resourceCulture);
            }
        }
    }
}
