//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAreaDeliveryService : SkyWeb.DatVM.Data.IBaseService<AreaDelivery>
    {
    }
    
    public partial class AreaDeliveryService : SkyWeb.DatVM.Data.BaseService<AreaDelivery>, IAreaDeliveryService
    {
        public AreaDeliveryService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAreaDeliveryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
