//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IArticleService : SkyWeb.DatVM.Data.IBaseService<Article>
    {
    }
    
    public partial class ArticleService : SkyWeb.DatVM.Data.BaseService<Article>, IArticleService
    {
        public ArticleService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IArticleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
