//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAspNetUserRoleService : SkyWeb.DatVM.Data.IBaseService<AspNetUserRole>
    {
    }
    
    public partial class AspNetUserRoleService : SkyWeb.DatVM.Data.BaseService<AspNetUserRole>, IAspNetUserRoleService
    {
        public AspNetUserRoleService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAspNetUserRoleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
