//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAttendanceService : SkyWeb.DatVM.Data.IBaseService<Attendance>
    {
    }
    
    public partial class AttendanceService : SkyWeb.DatVM.Data.BaseService<Attendance>, IAttendanceService
    {
        public AttendanceService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAttendanceRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
