//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAttendanceDateService : SkyWeb.DatVM.Data.IBaseService<AttendanceDate>
    {
    }
    
    public partial class AttendanceDateService : SkyWeb.DatVM.Data.BaseService<AttendanceDate>, IAttendanceDateService
    {
        public AttendanceDateService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAttendanceDateRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
