//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IBlogPostService : SkyWeb.DatVM.Data.IBaseService<BlogPost>
    {
    }
    
    public partial class BlogPostService : SkyWeb.DatVM.Data.BaseService<BlogPost>, IBlogPostService
    {
        public BlogPostService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IBlogPostRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
