//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IBlogPostCollectionItemMappingService : SkyWeb.DatVM.Data.IBaseService<BlogPostCollectionItemMapping>
    {
    }
    
    public partial class BlogPostCollectionItemMappingService : SkyWeb.DatVM.Data.BaseService<BlogPostCollectionItemMapping>, IBlogPostCollectionItemMappingService
    {
        public BlogPostCollectionItemMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IBlogPostCollectionItemMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
