//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICategoryExtraMappingService : SkyWeb.DatVM.Data.IBaseService<CategoryExtraMapping>
    {
    }
    
    public partial class CategoryExtraMappingService : SkyWeb.DatVM.Data.BaseService<CategoryExtraMapping>, ICategoryExtraMappingService
    {
        public CategoryExtraMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICategoryExtraMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
