//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IContactService : SkyWeb.DatVM.Data.IBaseService<Contact>
    {
    }
    
    public partial class ContactService : SkyWeb.DatVM.Data.BaseService<Contact>, IContactService
    {
        public ContactService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IContactRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
