//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICostService : SkyWeb.DatVM.Data.IBaseService<Cost>
    {
    }
    
    public partial class CostService : SkyWeb.DatVM.Data.BaseService<Cost>, ICostService
    {
        public CostService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICostRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
