//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICouponProviderService : SkyWeb.DatVM.Data.IBaseService<CouponProvider>
    {
    }
    
    public partial class CouponProviderService : SkyWeb.DatVM.Data.BaseService<CouponProvider>, ICouponProviderService
    {
        public CouponProviderService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICouponProviderRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
