//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICustomerFeedbackService : SkyWeb.DatVM.Data.IBaseService<CustomerFeedback>
    {
    }
    
    public partial class CustomerFeedbackService : SkyWeb.DatVM.Data.BaseService<CustomerFeedback>, ICustomerFeedbackService
    {
        public CustomerFeedbackService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICustomerFeedbackRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
