//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICustomerProductMappingService : SkyWeb.DatVM.Data.IBaseService<CustomerProductMapping>
    {
    }
    
    public partial class CustomerProductMappingService : SkyWeb.DatVM.Data.BaseService<CustomerProductMapping>, ICustomerProductMappingService
    {
        public CustomerProductMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICustomerProductMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
