//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICustomerFilterService : SkyWeb.DatVM.Data.IBaseService<CustomerFilter>
    {
    }
    
    public partial class CustomerFilterService : SkyWeb.DatVM.Data.BaseService<CustomerFilter>, ICustomerFilterService
    {
        public CustomerFilterService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICustomerFilterRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
