//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IDeliveryInfoService : SkyWeb.DatVM.Data.IBaseService<DeliveryInfo>
    {
    }
    
    public partial class DeliveryInfoService : SkyWeb.DatVM.Data.BaseService<DeliveryInfo>, IDeliveryInfoService
    {
        public DeliveryInfoService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IDeliveryInfoRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
