//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IEmployeeFingerService : SkyWeb.DatVM.Data.IBaseService<EmployeeFinger>
    {
    }
    
    public partial class EmployeeFingerService : SkyWeb.DatVM.Data.BaseService<EmployeeFinger>, IEmployeeFingerService
    {
        public EmployeeFingerService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IEmployeeFingerRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
