//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IEmployeeInStoreService : SkyWeb.DatVM.Data.IBaseService<EmployeeInStore>
    {
    }
    
    public partial class EmployeeInStoreService : SkyWeb.DatVM.Data.BaseService<EmployeeInStore>, IEmployeeInStoreService
    {
        public EmployeeInStoreService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IEmployeeInStoreRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
