//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IEmployeeService : SkyWeb.DatVM.Data.IBaseService<Employee>
    {
    }
    
    public partial class EmployeeService : SkyWeb.DatVM.Data.BaseService<Employee>, IEmployeeService
    {
        public EmployeeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IEmployeeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
