//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IEventLocationService : SkyWeb.DatVM.Data.IBaseService<EventLocation>
    {
    }
    
    public partial class EventLocationService : SkyWeb.DatVM.Data.BaseService<EventLocation>, IEventLocationService
    {
        public EventLocationService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IEventLocationRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
