//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IFingerScanMachineService : SkyWeb.DatVM.Data.IBaseService<FingerScanMachine>
    {
    }
    
    public partial class FingerScanMachineService : SkyWeb.DatVM.Data.BaseService<FingerScanMachine>, IFingerScanMachineService
    {
        public FingerScanMachineService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IFingerScanMachineRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
