//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IImageCollectionService : SkyWeb.DatVM.Data.IBaseService<ImageCollection>
    {
    }
    
    public partial class ImageCollectionService : SkyWeb.DatVM.Data.BaseService<ImageCollection>, IImageCollectionService
    {
        public ImageCollectionService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IImageCollectionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
