//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IImageCollectionItemService : SkyWeb.DatVM.Data.IBaseService<ImageCollectionItem>
    {
    }
    
    public partial class ImageCollectionItemService : SkyWeb.DatVM.Data.BaseService<ImageCollectionItem>, IImageCollectionItemService
    {
        public ImageCollectionItemService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IImageCollectionItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
