//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IInventoryDateReportService : SkyWeb.DatVM.Data.IBaseService<InventoryDateReport>
    {
    }
    
    public partial class InventoryDateReportService : SkyWeb.DatVM.Data.BaseService<InventoryDateReport>, IInventoryDateReportService
    {
        public InventoryDateReportService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IInventoryDateReportRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
