//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IInventoryReceiptService : SkyWeb.DatVM.Data.IBaseService<InventoryReceipt>
    {
    }
    
    public partial class InventoryReceiptService : SkyWeb.DatVM.Data.BaseService<InventoryReceipt>, IInventoryReceiptService
    {
        public InventoryReceiptService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IInventoryReceiptRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
