//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IInventoryCheckingItemService : SkyWeb.DatVM.Data.IBaseService<InventoryCheckingItem>
    {
    }
    
    public partial class InventoryCheckingItemService : SkyWeb.DatVM.Data.BaseService<InventoryCheckingItem>, IInventoryCheckingItemService
    {
        public InventoryCheckingItemService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IInventoryCheckingItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
