//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ILanguageValueService : SkyWeb.DatVM.Data.IBaseService<LanguageValue>
    {
    }
    
    public partial class LanguageValueService : SkyWeb.DatVM.Data.BaseService<LanguageValue>, ILanguageValueService
    {
        public LanguageValueService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ILanguageValueRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
