//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ILanguageKeyService : SkyWeb.DatVM.Data.IBaseService<LanguageKey>
    {
    }
    
    public partial class LanguageKeyService : SkyWeb.DatVM.Data.BaseService<LanguageKey>, ILanguageKeyService
    {
        public LanguageKeyService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ILanguageKeyRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
