//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IMachineConnectService : SkyWeb.DatVM.Data.IBaseService<MachineConnect>
    {
    }
    
    public partial class MachineConnectService : SkyWeb.DatVM.Data.BaseService<MachineConnect>, IMachineConnectService
    {
        public MachineConnectService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IMachineConnectRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
