//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IMembershipCardService : SkyWeb.DatVM.Data.IBaseService<MembershipCard>
    {
    }
    
    public partial class MembershipCardService : SkyWeb.DatVM.Data.BaseService<MembershipCard>, IMembershipCardService
    {
        public MembershipCardService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IMembershipCardRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
