//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IMembershipCardTypeService : SkyWeb.DatVM.Data.IBaseService<MembershipCardType>
    {
    }
    
    public partial class MembershipCardTypeService : SkyWeb.DatVM.Data.BaseService<MembershipCardType>, IMembershipCardTypeService
    {
        public MembershipCardTypeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IMembershipCardTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
