//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IMenuService : SkyWeb.DatVM.Data.IBaseService<Menu>
    {
    }
    
    public partial class MenuService : SkyWeb.DatVM.Data.BaseService<Menu>, IMenuService
    {
        public MenuService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IMenuRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
