//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IMenuRoleService : SkyWeb.DatVM.Data.IBaseService<MenuRole>
    {
    }
    
    public partial class MenuRoleService : SkyWeb.DatVM.Data.BaseService<MenuRole>, IMenuRoleService
    {
        public MenuRoleService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IMenuRoleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
