//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IOrderFeeItemService : SkyWeb.DatVM.Data.IBaseService<OrderFeeItem>
    {
    }
    
    public partial class OrderFeeItemService : SkyWeb.DatVM.Data.BaseService<OrderFeeItem>, IOrderFeeItemService
    {
        public OrderFeeItemService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IOrderFeeItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
