//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IOrderPromotionMappingService : SkyWeb.DatVM.Data.IBaseService<OrderPromotionMapping>
    {
    }
    
    public partial class OrderPromotionMappingService : SkyWeb.DatVM.Data.BaseService<OrderPromotionMapping>, IOrderPromotionMappingService
    {
        public OrderPromotionMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IOrderPromotionMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
