//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPaymentPartnerService : SkyWeb.DatVM.Data.IBaseService<PaymentPartner>
    {
    }
    
    public partial class PaymentPartnerService : SkyWeb.DatVM.Data.BaseService<PaymentPartner>, IPaymentPartnerService
    {
        public PaymentPartnerService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPaymentPartnerRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
