//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPaymentReportService : SkyWeb.DatVM.Data.IBaseService<PaymentReport>
    {
    }
    
    public partial class PaymentReportService : SkyWeb.DatVM.Data.BaseService<PaymentReport>, IPaymentReportService
    {
        public PaymentReportService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPaymentReportRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
