//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPosConfigService : SkyWeb.DatVM.Data.IBaseService<PosConfig>
    {
    }
    
    public partial class PosConfigService : SkyWeb.DatVM.Data.BaseService<PosConfig>, IPosConfigService
    {
        public PosConfigService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPosConfigRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
