//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPosService : SkyWeb.DatVM.Data.IBaseService<Pos>
    {
    }
    
    public partial class PosService : SkyWeb.DatVM.Data.BaseService<Pos>, IPosService
    {
        public PosService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPosRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
