//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPriceGroupService : SkyWeb.DatVM.Data.IBaseService<PriceGroup>
    {
    }
    
    public partial class PriceGroupService : SkyWeb.DatVM.Data.BaseService<PriceGroup>, IPriceGroupService
    {
        public PriceGroupService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPriceGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
