//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProductDetailMappingService : SkyWeb.DatVM.Data.IBaseService<ProductDetailMapping>
    {
    }
    
    public partial class ProductDetailMappingService : SkyWeb.DatVM.Data.BaseService<ProductDetailMapping>, IProductDetailMappingService
    {
        public ProductDetailMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProductDetailMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
