//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProductCollectionItemMappingService : SkyWeb.DatVM.Data.IBaseService<ProductCollectionItemMapping>
    {
    }
    
    public partial class ProductCollectionItemMappingService : SkyWeb.DatVM.Data.BaseService<ProductCollectionItemMapping>, IProductCollectionItemMappingService
    {
        public ProductCollectionItemMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProductCollectionItemMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
