//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProductItemCategoryService : SkyWeb.DatVM.Data.IBaseService<ProductItemCategory>
    {
    }
    
    public partial class ProductItemCategoryService : SkyWeb.DatVM.Data.BaseService<ProductItemCategory>, IProductItemCategoryService
    {
        public ProductItemCategoryService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProductItemCategoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
