//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProductItemService : SkyWeb.DatVM.Data.IBaseService<ProductItem>
    {
    }
    
    public partial class ProductItemService : SkyWeb.DatVM.Data.BaseService<ProductItem>, IProductItemService
    {
        public ProductItemService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProductItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
