//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProductCategoryService : SkyWeb.DatVM.Data.IBaseService<ProductCategory>
    {
    }
    
    public partial class ProductCategoryService : SkyWeb.DatVM.Data.BaseService<ProductCategory>, IProductCategoryService
    {
        public ProductCategoryService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProductCategoryRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
