//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProductSpecificationService : SkyWeb.DatVM.Data.IBaseService<ProductSpecification>
    {
    }
    
    public partial class ProductSpecificationService : SkyWeb.DatVM.Data.BaseService<ProductSpecification>, IProductSpecificationService
    {
        public ProductSpecificationService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProductSpecificationRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
