//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProductComboDetailService : SkyWeb.DatVM.Data.IBaseService<ProductComboDetail>
    {
    }
    
    public partial class ProductComboDetailService : SkyWeb.DatVM.Data.BaseService<ProductComboDetail>, IProductComboDetailService
    {
        public ProductComboDetailService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProductComboDetailRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
