//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPromotionPartnerService : SkyWeb.DatVM.Data.IBaseService<PromotionPartner>
    {
    }
    
    public partial class PromotionPartnerService : SkyWeb.DatVM.Data.BaseService<PromotionPartner>, IPromotionPartnerService
    {
        public PromotionPartnerService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPromotionPartnerRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
