//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPromotionStoreMappingService : SkyWeb.DatVM.Data.IBaseService<PromotionStoreMapping>
    {
    }
    
    public partial class PromotionStoreMappingService : SkyWeb.DatVM.Data.BaseService<PromotionStoreMapping>, IPromotionStoreMappingService
    {
        public PromotionStoreMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPromotionStoreMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
