//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IProviderProductItemMappingService : SkyWeb.DatVM.Data.IBaseService<ProviderProductItemMapping>
    {
    }
    
    public partial class ProviderProductItemMappingService : SkyWeb.DatVM.Data.BaseService<ProviderProductItemMapping>, IProviderProductItemMappingService
    {
        public ProviderProductItemMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IProviderProductItemMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
