//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IRatingProductService : SkyWeb.DatVM.Data.IBaseService<RatingProduct>
    {
    }
    
    public partial class RatingProductService : SkyWeb.DatVM.Data.BaseService<RatingProduct>, IRatingProductService
    {
        public RatingProductService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IRatingProductRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
