//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IRatingStarService : SkyWeb.DatVM.Data.IBaseService<RatingStar>
    {
    }
    
    public partial class RatingStarService : SkyWeb.DatVM.Data.BaseService<RatingStar>, IRatingStarService
    {
        public RatingStarService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IRatingStarRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
