//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IRoomCategoryPriceGroupMappingService : SkyWeb.DatVM.Data.IBaseService<RoomCategoryPriceGroupMapping>
    {
    }
    
    public partial class RoomCategoryPriceGroupMappingService : SkyWeb.DatVM.Data.BaseService<RoomCategoryPriceGroupMapping>, IRoomCategoryPriceGroupMappingService
    {
        public RoomCategoryPriceGroupMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IRoomCategoryPriceGroupMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
