//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreWebSettingService : SkyWeb.DatVM.Data.IBaseService<StoreWebSetting>
    {
    }
    
    public partial class StoreWebSettingService : SkyWeb.DatVM.Data.BaseService<StoreWebSetting>, IStoreWebSettingService
    {
        public StoreWebSettingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreWebSettingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
