//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreDomainService : SkyWeb.DatVM.Data.IBaseService<StoreDomain>
    {
    }
    
    public partial class StoreDomainService : SkyWeb.DatVM.Data.BaseService<StoreDomain>, IStoreDomainService
    {
        public StoreDomainService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreDomainRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
