//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreService : SkyWeb.DatVM.Data.IBaseService<Store>
    {
    }
    
    public partial class StoreService : SkyWeb.DatVM.Data.BaseService<Store>, IStoreService
    {
        public StoreService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
