//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreUserService : SkyWeb.DatVM.Data.IBaseService<StoreUser>
    {
    }
    
    public partial class StoreUserService : SkyWeb.DatVM.Data.BaseService<StoreUser>, IStoreUserService
    {
        public StoreUserService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreUserRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
