//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreWebRouteModelService : SkyWeb.DatVM.Data.IBaseService<StoreWebRouteModel>
    {
    }
    
    public partial class StoreWebRouteModelService : SkyWeb.DatVM.Data.BaseService<StoreWebRouteModel>, IStoreWebRouteModelService
    {
        public StoreWebRouteModelService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreWebRouteModelRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
