//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreGroupService : SkyWeb.DatVM.Data.IBaseService<StoreGroup>
    {
    }
    
    public partial class StoreGroupService : SkyWeb.DatVM.Data.BaseService<StoreGroup>, IStoreGroupService
    {
        public StoreGroupService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
