//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreThemeService : SkyWeb.DatVM.Data.IBaseService<StoreTheme>
    {
    }
    
    public partial class StoreThemeService : SkyWeb.DatVM.Data.BaseService<StoreTheme>, IStoreThemeService
    {
        public StoreThemeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreThemeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
