//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreGroupMappingService : SkyWeb.DatVM.Data.IBaseService<StoreGroupMapping>
    {
    }
    
    public partial class StoreGroupMappingService : SkyWeb.DatVM.Data.BaseService<StoreGroupMapping>, IStoreGroupMappingService
    {
        public StoreGroupMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreGroupMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
