//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IStoreWebRouteService : SkyWeb.DatVM.Data.IBaseService<StoreWebRoute>
    {
    }
    
    public partial class StoreWebRouteService : SkyWeb.DatVM.Data.BaseService<StoreWebRoute>, IStoreWebRouteService
    {
        public StoreWebRouteService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IStoreWebRouteRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
