//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ISubRentGroupService : SkyWeb.DatVM.Data.IBaseService<SubRentGroup>
    {
    }
    
    public partial class SubRentGroupService : SkyWeb.DatVM.Data.BaseService<SubRentGroup>, ISubRentGroupService
    {
        public SubRentGroupService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ISubRentGroupRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
