//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ISystemPartnerMappingService : SkyWeb.DatVM.Data.IBaseService<SystemPartnerMapping>
    {
    }
    
    public partial class SystemPartnerMappingService : SkyWeb.DatVM.Data.BaseService<SystemPartnerMapping>, ISystemPartnerMappingService
    {
        public SystemPartnerMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ISystemPartnerMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
