//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ITagMappingService : SkyWeb.DatVM.Data.IBaseService<TagMapping>
    {
    }
    
    public partial class TagMappingService : SkyWeb.DatVM.Data.BaseService<TagMapping>, ITagMappingService
    {
        public TagMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ITagMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
