//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IUsersInRoleService : SkyWeb.DatVM.Data.IBaseService<UsersInRole>
    {
    }
    
    public partial class UsersInRoleService : SkyWeb.DatVM.Data.BaseService<UsersInRole>, IUsersInRoleService
    {
        public UsersInRoleService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IUsersInRoleRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
