//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVATOrderMappingService : SkyWeb.DatVM.Data.IBaseService<VATOrderMapping>
    {
    }
    
    public partial class VATOrderMappingService : SkyWeb.DatVM.Data.BaseService<VATOrderMapping>, IVATOrderMappingService
    {
        public VATOrderMappingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IVATOrderMappingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
