//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IWardService : SkyWeb.DatVM.Data.IBaseService<Ward>
    {
    }
    
    public partial class WardService : SkyWeb.DatVM.Data.BaseService<Ward>, IWardService
    {
        public WardService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IWardRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
