//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IWebCustomerFeedbackService : SkyWeb.DatVM.Data.IBaseService<WebCustomerFeedback>
    {
    }
    
    public partial class WebCustomerFeedbackService : SkyWeb.DatVM.Data.BaseService<WebCustomerFeedback>, IWebCustomerFeedbackService
    {
        public WebCustomerFeedbackService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IWebCustomerFeedbackRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
