//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IWebElementTypeService : SkyWeb.DatVM.Data.IBaseService<WebElementType>
    {
    }
    
    public partial class WebElementTypeService : SkyWeb.DatVM.Data.BaseService<WebElementType>, IWebElementTypeService
    {
        public WebElementTypeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IWebElementTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
