//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IWebPageService : SkyWeb.DatVM.Data.IBaseService<WebPage>
    {
    }
    
    public partial class WebPageService : SkyWeb.DatVM.Data.BaseService<WebPage>, IWebPageService
    {
        public WebPageService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IWebPageRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
