//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.SkyAdmin.Manage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wisky.SkyAdmin.Manage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A/C No..
        /// </summary>
        internal static string ACCOUNT_NO_EN {
            get {
                return ResourceManager.GetString("ACCOUNT_NO_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        internal static string ACCOUNT_NO_VN {
            get {
                return ResourceManager.GetString("ACCOUNT_NO_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ADDRESS_EN {
            get {
                return ResourceManager.GetString("ADDRESS_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string ADDRESS_VN {
            get {
                return ResourceManager.GetString("ADDRESS_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        internal static string AMOUNT_EN {
            get {
                return ResourceManager.GetString("AMOUNT_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        internal static string AMOUNT_VN {
            get {
                return ResourceManager.GetString("AMOUNT_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TỈ.
        /// </summary>
        internal static string BILLIONS_VN {
            get {
                return ResourceManager.GetString("BILLIONS_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string BIRTHDAY {
            get {
                return ResourceManager.GetString("BIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string BIRTHDAY_FORMAT {
            get {
                return ResourceManager.GetString("BIRTHDAY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer.
        /// </summary>
        internal static string BUYER_EN {
            get {
                return ResourceManager.GetString("BUYER_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người mua hàng.
        /// </summary>
        internal static string BUYER_VN {
            get {
                return ResourceManager.GetString("BUYER_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string COLON {
            get {
                return ResourceManager.GetString("COLON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string COMMA {
            get {
                return ResourceManager.GetString("COMMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string COMPANY_EN {
            get {
                return ResourceManager.GetString("COMPANY_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        internal static string COMPANY_VN {
            get {
                return ResourceManager.GetString("COMPANY_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONG.
        /// </summary>
        internal static string CURRENCY_EN {
            get {
                return ResourceManager.GetString("CURRENCY_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐỒNG.
        /// </summary>
        internal static string CURRENCY_VN {
            get {
                return ResourceManager.GetString("CURRENCY_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string CUSTOMER_EN {
            get {
                return ResourceManager.GetString("CUSTOMER_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer_List.
        /// </summary>
        internal static string CUSTOMER_LIST {
            get {
                return ResourceManager.GetString("CUSTOMER_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên người mua hàng.
        /// </summary>
        internal static string CUSTOMER_VN {
            get {
                return ResourceManager.GetString("CUSTOMER_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DATE_EN {
            get {
                return ResourceManager.GetString("DATE_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd-MM-yyyy hh-mm-ss tt.
        /// </summary>
        internal static string DATE_TIME_FORMAT {
            get {
                return ResourceManager.GetString("DATE_TIME_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        internal static string DATE_VN {
            get {
                return ResourceManager.GetString("DATE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DESCRIPTION_EN {
            get {
                return ResourceManager.GetString("DESCRIPTION_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng hóa, dịch vụ.
        /// </summary>
        internal static string DESCRIPTION_VN {
            get {
                return ResourceManager.GetString("DESCRIPTION_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director.
        /// </summary>
        internal static string DIRECTOR_EN {
            get {
                return ResourceManager.GetString("DIRECTOR_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ trưởng đơn vị.
        /// </summary>
        internal static string DIRECTOR_VN {
            get {
                return ResourceManager.GetString("DIRECTOR_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string DOT {
            get {
                return ResourceManager.GetString("DOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        internal static string DOUBLE_WHITE_SPACE {
            get {
                return ResourceManager.GetString("DOUBLE_WHITE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string EIGHT {
            get {
                return ResourceManager.GetString("EIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TÁM.
        /// </summary>
        internal static string EIGHT_VN {
            get {
                return ResourceManager.GetString("EIGHT_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string EQUAL {
            get {
                return ResourceManager.GetString("EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xuất hóa đơn VAT!.
        /// </summary>
        internal static string ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string FEMALE_VN {
            get {
                return ResourceManager.GetString("FEMALE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st copy: File.
        /// </summary>
        internal static string FIRST_COPY_EN {
            get {
                return ResourceManager.GetString("FIRST_COPY_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên 1: Lưu.
        /// </summary>
        internal static string FIRST_COPY_VN {
            get {
                return ResourceManager.GetString("FIRST_COPY_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string FIVE {
            get {
                return ResourceManager.GetString("FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NĂM.
        /// </summary>
        internal static string FIVE_1_VN {
            get {
                return ResourceManager.GetString("FIVE_1_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LĂM.
        /// </summary>
        internal static string FIVE_2_VN {
            get {
                return ResourceManager.GetString("FIVE_2_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \fonts\times.ttf.
        /// </summary>
        internal static string FONT_PATH {
            get {
                return ResourceManager.GetString("FONT_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string FORM_EN {
            get {
                return ResourceManager.GetString("FORM_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01GTKT2/001.
        /// </summary>
        internal static string FORM_VALUE {
            get {
                return ResourceManager.GetString("FORM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mẫu số.
        /// </summary>
        internal static string FORM_VN {
            get {
                return ResourceManager.GetString("FORM_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string FOUR {
            get {
                return ResourceManager.GetString("FOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BỐN.
        /// </summary>
        internal static string FOUR_VN {
            get {
                return ResourceManager.GetString("FOUR_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        internal static string GENDER_VN {
            get {
                return ResourceManager.GetString("GENDER_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand amount.
        /// </summary>
        internal static string GRAND_TOTAL_EN {
            get {
                return ResourceManager.GetString("GRAND_TOTAL_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền thanh toán.
        /// </summary>
        internal static string GRAND_TOTAL_VN {
            get {
                return ResourceManager.GetString("GRAND_TOTAL_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 52 Pasteur, Phường Bến Nghé, Quận 1, TP. HCM.
        /// </summary>
        internal static string HEADER_ADDRESS {
            get {
                return ResourceManager.GetString("HEADER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Elbow-room Restaurant Co., Ltd.
        /// </summary>
        internal static string HEADER_COMP_EN {
            get {
                return ResourceManager.GetString("HEADER_COMP_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÔNG TY TNHH TRỞ TAY QUÁN.
        /// </summary>
        internal static string HEADER_COMP_VN {
            get {
                return ResourceManager.GetString("HEADER_COMP_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Content/images/logoElbowRoom.jpg.
        /// </summary>
        internal static string HEADER_LOGO {
            get {
                return ResourceManager.GetString("HEADER_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (08) 3821 4327.
        /// </summary>
        internal static string HEADER_TEL {
            get {
                return ResourceManager.GetString("HEADER_TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 3 0 8 6 1 8 4 9 4.
        /// </summary>
        internal static string HEADER_VAT_CODE {
            get {
                return ResourceManager.GetString("HEADER_VAT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRĂM.
        /// </summary>
        internal static string HUNDREDS_VN {
            get {
                return ResourceManager.GetString("HUNDREDS_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In word.
        /// </summary>
        internal static string IN_WORD_EN {
            get {
                return ResourceManager.GetString("IN_WORD_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tiền viết bằng chữ.
        /// </summary>
        internal static string IN_WORD_VN {
            get {
                return ResourceManager.GetString("IN_WORD_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string LEFT_PARENTHESIS {
            get {
                return ResourceManager.GetString("LEFT_PARENTHESIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string MALE_VN {
            get {
                return ResourceManager.GetString("MALE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIỆU.
        /// </summary>
        internal static string MILLIONS_VN {
            get {
                return ResourceManager.GetString("MILLIONS_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string MONTH_EN {
            get {
                return ResourceManager.GetString("MONTH_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tháng.
        /// </summary>
        internal static string MONTH_VN {
            get {
                return ResourceManager.GetString("MONTH_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string MULTIPLY {
            get {
                return ResourceManager.GetString("MULTIPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        internal static string NAME_VN {
            get {
                return ResourceManager.GetString("NAME_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string NINE {
            get {
                return ResourceManager.GetString("NINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHÍN.
        /// </summary>
        internal static string NINE_VN {
            get {
                return ResourceManager.GetString("NINE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string NO_EN {
            get {
                return ResourceManager.GetString("NO_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số.
        /// </summary>
        internal static string NO_VN {
            get {
                return ResourceManager.GetString("NO_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần kiểm tra đối chiếu khi lập, giao, nhận hóa đơn.
        /// </summary>
        internal static string NOTE_VN {
            get {
                return ResourceManager.GetString("NOTE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ONE {
            get {
                return ResourceManager.GetString("ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MỘT.
        /// </summary>
        internal static string ONE_1_VN {
            get {
                return ResourceManager.GetString("ONE_1_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MỐT.
        /// </summary>
        internal static string ONE_2_VN {
            get {
                return ResourceManager.GetString("ONE_2_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string ORDER_NO_VN {
            get {
                return ResourceManager.GetString("ORDER_NO_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        internal static string PAYMENT_METHOD_EN {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức thanh toán.
        /// </summary>
        internal static string PAYMENT_METHOD_VN {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string QUANTITY_EN {
            get {
                return ResourceManager.GetString("QUANTITY_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string QUANTITY_VN {
            get {
                return ResourceManager.GetString("QUANTITY_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string RIGHT_PARENTHESIS {
            get {
                return ResourceManager.GetString("RIGHT_PARENTHESIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd copy: Customer.
        /// </summary>
        internal static string SECOND_COPY_EN {
            get {
                return ResourceManager.GetString("SECOND_COPY_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên 2: Giao cho người mua.
        /// </summary>
        internal static string SECOND_COPY_VN {
            get {
                return ResourceManager.GetString("SECOND_COPY_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        internal static string SELLER_EN {
            get {
                return ResourceManager.GetString("SELLER_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người bán hàng.
        /// </summary>
        internal static string SELLER_VN {
            get {
                return ResourceManager.GetString("SELLER_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string SERIAL_EN {
            get {
                return ResourceManager.GetString("SERIAL_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TQ/13T.
        /// </summary>
        internal static string SERIAL_VALUE {
            get {
                return ResourceManager.GetString("SERIAL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký hiệu.
        /// </summary>
        internal static string SERIAL_VN {
            get {
                return ResourceManager.GetString("SERIAL_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string SEVEN {
            get {
                return ResourceManager.GetString("SEVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BẢY.
        /// </summary>
        internal static string SEVEN_VN {
            get {
                return ResourceManager.GetString("SEVEN_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign &amp; full name.
        /// </summary>
        internal static string SIGN_AND_FULLNAME_EN {
            get {
                return ResourceManager.GetString("SIGN_AND_FULLNAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký, ghi rõ họ tên.
        /// </summary>
        internal static string SIGN_AND_FULLNAME_VN {
            get {
                return ResourceManager.GetString("SIGN_AND_FULLNAME_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign, stamp &amp; full name.
        /// </summary>
        internal static string SIGN_STAMP_AND_FULLNAME_EN {
            get {
                return ResourceManager.GetString("SIGN_STAMP_AND_FULLNAME_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký, đóng dấu, ghi rõ họ tên.
        /// </summary>
        internal static string SIGN_STAMP_AND_FULLNAME_VN {
            get {
                return ResourceManager.GetString("SIGN_STAMP_AND_FULLNAME_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string SIX {
            get {
                return ResourceManager.GetString("SIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SÁU.
        /// </summary>
        internal static string SIX_VN {
            get {
                return ResourceManager.GetString("SIX_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        internal static string TEL_EN {
            get {
                return ResourceManager.GetString("TEL_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        internal static string TEL_VN {
            get {
                return ResourceManager.GetString("TEL_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MƯỜI.
        /// </summary>
        internal static string TENTH_1_VN {
            get {
                return ResourceManager.GetString("TENTH_1_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MƯƠI.
        /// </summary>
        internal static string TENTH_2_VN {
            get {
                return ResourceManager.GetString("TENTH_2_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGHÌN.
        /// </summary>
        internal static string THOUSANDS_VN {
            get {
                return ResourceManager.GetString("THOUSANDS_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string THREE {
            get {
                return ResourceManager.GetString("THREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BA.
        /// </summary>
        internal static string THREE_VN {
            get {
                return ResourceManager.GetString("THREE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount.
        /// </summary>
        internal static string TOTAL_AMOUNT_EN {
            get {
                return ResourceManager.GetString("TOTAL_AMOUNT_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng tiền hàng.
        /// </summary>
        internal static string TOTAL_AMOUNT_VN {
            get {
                return ResourceManager.GetString("TOTAL_AMOUNT_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    .
        /// </summary>
        internal static string TRIPLE_WHITE_SPACE {
            get {
                return ResourceManager.GetString("TRIPLE_WHITE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string TWO {
            get {
                return ResourceManager.GetString("TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAI.
        /// </summary>
        internal static string TWO_VN {
            get {
                return ResourceManager.GetString("TWO_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định.
        /// </summary>
        internal static string UNDEFINE_VN {
            get {
                return ResourceManager.GetString("UNDEFINE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        internal static string UNDERSCORE {
            get {
                return ResourceManager.GetString("UNDERSCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string UNIT_EN {
            get {
                return ResourceManager.GetString("UNIT_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        internal static string UNIT_PRICE_EN {
            get {
                return ResourceManager.GetString("UNIT_PRICE_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        internal static string UNIT_PRICE_VN {
            get {
                return ResourceManager.GetString("UNIT_PRICE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐVT.
        /// </summary>
        internal static string UNIT_VN {
            get {
                return ResourceManager.GetString("UNIT_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10%.
        /// </summary>
        internal static string VAT {
            get {
                return ResourceManager.GetString("VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT amount.
        /// </summary>
        internal static string VAT_AMOUNT_EN {
            get {
                return ResourceManager.GetString("VAT_AMOUNT_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thuế GTGT.
        /// </summary>
        internal static string VAT_AMOUNT_VN {
            get {
                return ResourceManager.GetString("VAT_AMOUNT_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Code.
        /// </summary>
        internal static string VAT_CODE_EN {
            get {
                return ResourceManager.GetString("VAT_CODE_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        internal static string VAT_CODE_VN {
            get {
                return ResourceManager.GetString("VAT_CODE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT INVOICE.
        /// </summary>
        internal static string VAT_INVOICE_EN {
            get {
                return ResourceManager.GetString("VAT_INVOICE_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT_Invoice.
        /// </summary>
        internal static string VAT_INVOICE_FILE_NAME {
            get {
                return ResourceManager.GetString("VAT_INVOICE_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HÓA ĐƠN GIÁ TRỊ GIA TĂNG.
        /// </summary>
        internal static string VAT_INVOICE_VN {
            get {
                return ResourceManager.GetString("VAT_INVOICE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT rate.
        /// </summary>
        internal static string VAT_RATE_EN {
            get {
                return ResourceManager.GetString("VAT_RATE_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuế suất GTGT.
        /// </summary>
        internal static string VAT_RATE_VN {
            get {
                return ResourceManager.GetString("VAT_RATE_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string WHITE_SPACE {
            get {
                return ResourceManager.GetString("WHITE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string YEAR_EN {
            get {
                return ResourceManager.GetString("YEAR_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to năm.
        /// </summary>
        internal static string YEAR_VN {
            get {
                return ResourceManager.GetString("YEAR_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ZERO {
            get {
                return ResourceManager.GetString("ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KHÔNG.
        /// </summary>
        internal static string ZERO_1_VN {
            get {
                return ResourceManager.GetString("ZERO_1_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LẺ.
        /// </summary>
        internal static string ZERO_2_VN {
            get {
                return ResourceManager.GetString("ZERO_2_VN", resourceCulture);
            }
        }
    }
}
