//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Repositories
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPaymentReportRepository : SkyWeb.DatVM.Data.IBaseRepository<PaymentReport>
    {
    }
    
    public partial class PaymentReportRepository : SkyWeb.DatVM.Data.BaseRepository<PaymentReport>, IPaymentReportRepository
    {
    	public PaymentReportRepository(System.Data.Entity.DbContext dbContext) : base(dbContext)
    	{
    	}
    }
}
