//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Article>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Decription { get; set; }
    			public virtual string ContentHTML { get; set; }
    			public virtual System.DateTime DateCreate { get; set; }
    			public virtual bool IsAvailable { get; set; }
    			public virtual string Thumbnail { get; set; }
    	
    	public ArticleViewModel() : base() { }
    	public ArticleViewModel(HmsService.Models.Entities.Article entity) : base(entity) { }
    
    }
}
