//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserRoleViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.AspNetUserRole>
    {
    	
    			public virtual string UserId { get; set; }
    			public virtual string RoleId { get; set; }
    	
    	public AspNetUserRoleViewModel() : base() { }
    	public AspNetUserRoleViewModel(HmsService.Models.Entities.AspNetUserRole entity) : base(entity) { }
    
    }
}
