//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryExtraViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.CategoryExtra>
    {
    	
    			public virtual int CategoryExtraId { get; set; }
    			public virtual int PrimaryCategoryId { get; set; }
    			public virtual int ExtraCategoryId { get; set; }
    			public virtual bool IsEnable { get; set; }
    	
    	public CategoryExtraViewModel() : base() { }
    	public CategoryExtraViewModel(HmsService.Models.Entities.CategoryExtra entity) : base(entity) { }
    
    }
}
