//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckFingerViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.CheckFinger>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual Nullable<int> FingerScanMachineId { get; set; }
    			public virtual Nullable<int> EmployeeId { get; set; }
    			public virtual System.DateTime DateTime { get; set; }
    			public virtual Nullable<int> Mode { get; set; }
    			public virtual bool Active { get; set; }
    			public virtual Nullable<int> StoreId { get; set; }
    			public virtual string MachineNumber { get; set; }
    			public virtual string EmpEnrollNumber { get; set; }
    			public virtual Nullable<bool> IsUpdated { get; set; }
    			public virtual Nullable<int> BrandId { get; set; }
    			public virtual string LogCode { get; set; }
    	
    	public CheckFingerViewModel() : base() { }
    	public CheckFingerViewModel(HmsService.Models.Entities.CheckFinger entity) : base(entity) { }
    
    }
}
