//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponProviderViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.CouponProvider>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string ProviderName { get; set; }
    			public virtual bool IsActive { get; set; }
    	
    	public CouponProviderViewModel() : base() { }
    	public CouponProviderViewModel(HmsService.Models.Entities.CouponProvider entity) : base(entity) { }
    
    }
}
