//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLocationViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.EventLocation>
    {
    	
    			public virtual int LocationId { get; set; }
    			public virtual string LocationName { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public EventLocationViewModel() : base() { }
    	public EventLocationViewModel(HmsService.Models.Entities.EventLocation entity) : base(entity) { }
    
    }
}
