//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageValueViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.LanguageValue>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int LanguageKeyId { get; set; }
    			public virtual int LanguageId { get; set; }
    			public virtual string Value { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public LanguageValueViewModel() : base() { }
    	public LanguageValueViewModel(HmsService.Models.Entities.LanguageValue entity) : base(entity) { }
    
    }
}
