//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MembershipCardTypeViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.MembershipCardType>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string TypeName { get; set; }
    			public virtual string AppendCode { get; set; }
    			public virtual int BrandId { get; set; }
    			public virtual Nullable<bool> Active { get; set; }
    			public virtual Nullable<bool> IsMobile { get; set; }
    			public virtual Nullable<int> TypeLevel { get; set; }
    			public virtual Nullable<int> TypePoint { get; set; }
    	
    	public MembershipCardTypeViewModel() : base() { }
    	public MembershipCardTypeViewModel(HmsService.Models.Entities.MembershipCardType entity) : base(entity) { }
    
    }
}
