//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Pos>
    {
    	
    			public virtual int PosId { get; set; }
    			public virtual string MacId { get; set; }
    			public virtual string PosConfig { get; set; }
    			public virtual string PosCode { get; set; }
    	
    	public PosViewModel() : base() { }
    	public PosViewModel(HmsService.Models.Entities.Pos entity) : base(entity) { }
    
    }
}
