//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingProductViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.RatingProduct>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual string UserId { get; set; }
    			public virtual int ProductId { get; set; }
    			public virtual System.DateTime CreateTime { get; set; }
    			public virtual int Star { get; set; }
    			public virtual string ReviewContent { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public RatingProductViewModel() : base() { }
    	public RatingProductViewModel(HmsService.Models.Entities.RatingProduct entity) : base(entity) { }
    
    }
}
