//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreGroupMappingViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.StoreGroupMapping>
    {
    	
    			public virtual int ID { get; set; }
    			public virtual int StoreGroupID { get; set; }
    			public virtual int StoreID { get; set; }
    	
    	public StoreGroupMappingViewModel() : base() { }
    	public StoreGroupMappingViewModel(HmsService.Models.Entities.StoreGroupMapping entity) : base(entity) { }
    
    }
}
