//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDomainViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.StoreDomain>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int StoreId { get; set; }
    			public virtual string Protocol { get; set; }
    			public virtual string HostName { get; set; }
    			public virtual int Port { get; set; }
    			public virtual string Directory { get; set; }
    			public virtual bool Active { get; set; }
    	
    	public StoreDomainViewModel() : base() { }
    	public StoreDomainViewModel(HmsService.Models.Entities.StoreDomain entity) : base(entity) { }
    
    }
}
