//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateReportProductItemMappingViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.TemplateReportProductItemMapping>
    {
    	
    			public virtual int Id { get; set; }
    			public virtual int InventoryTemplateReportId { get; set; }
    			public virtual int ProductItemId { get; set; }
    			public virtual int MappingIndex { get; set; }
    	
    	public TemplateReportProductItemMappingViewModel() : base() { }
    	public TemplateReportProductItemMappingViewModel(HmsService.Models.Entities.TemplateReportProductItemMapping entity) : base(entity) { }
    
    }
}
