//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Sdk
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupApi : HmsService.Sdk.BaseSdkApi<HmsService.Models.Entities.Group, HmsService.ViewModels.GroupViewModel, HmsService.Models.Entities.Services.IGroupService>
    {
    	
    }
}
