//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Sdk
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceAdditionApi : HmsService.Sdk.BaseSdkApi<HmsService.Models.Entities.PriceAddition, HmsService.ViewModels.PriceAdditionViewModel, HmsService.Models.Entities.Services.IPriceAdditionService>
    {
    	
    }
}
